[package]
name = "omsupply-service"
version = "0.1.0"
description = "A crate that implements windows service methods"
keywords = ["windows", "service", "daemon"]
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[target.'cfg(windows)'.dependencies]
bitflags = "1.3"
err-derive = "0.3.1"
widestring = "1"
windows-service = "0.5.0"
server = { path = "../server", default-features = false }
service = { path = "../service" }
