[package]
name = "android"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "remote_server_android"

[dependencies]
repository = { path = "../repository" }
server = { path = "../server" }

jni = { version = "0.19.0"}
actix-web = { version= "3.3.2", features = ["openssl"] } # Versions >=v4 depend on Tokio v1.

[features]
default = ["repository/sqlite"]
postgres = ["repository/postgres"]
