server:
  port: 8000
sync:
  port: 2048
  username: "username"
  password: "password"
  interval: 300
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
