server:
  port: 8000
  # debug_no_access_control: true # enable this if you want to ignore API authorisation (dummy user will be used for all operations)
  # danger_allow_http: true # allow http in production mode
  cors_origins: [
      http://localhost:3003,
      https://demo-open.msupply.org,
      http://localhost:8000,
    ] # Used to set the allowed Origin in Cross Origin Requst Security
  base_dir: "app_data"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
logging:
  destination: Console
  level: Info

