[package]
name = "remote_server"
version = "0.1.0"
authors = ["will"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "remote_server"

[dependencies]
actix-cors = "0.5.4"
actix-rt = "1.1.0"
actix-web = "3.3.2" # When updating this to 4 (when it comes out), the tokio dependency will need to be bumped to at least 1.3.
async-trait = "0.1.16"
config = "0.11.0"
env_logger = "0.8.3"
futures-util = "0.3.15"
log = "0.4.14"
juniper = "0.15.5"
juniper_actix = "0.2.4"
serde = "1.0.126"
uuid = { version = "0.8", features = ["v4"] }
tokio = "0.2" # This must match the version actix-web depends on.

[dependencies.sqlx]
version = "0.4.1"
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "migrate",
    "offline"
]