[package]
name = "rust_server"
version = "0.1.0"
authors = ["will"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rust_server"

[dependencies]
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.5"
reqwest = "0.11.3"
tokio = "1.6.0"
