[package]
name = "rust_server"
version = "0.1.0"
authors = ["will"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rust_server"

[dependencies]
actix-web = "=4.0.0-beta.5"
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-rt = "2.2.0"
config = "0.11.0"
reqwest = "0.11.3"
serde = { version = "1", features = ["derive"] }
tokio = "1.6.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
env_logger = "0.8.3"
log = "0.4.14"
tracing-futures = "0.2.5"
tracing-bunyan-formatter = "0.2.4"

[dependencies.sqlx]
version = "0.5.1"
default-features = false
features = [
    "macros",
    "migrate",
    "postgres",
    "runtime-actix-rustls",
    "uuid"
]
