[package]
name = "omsupply_server"
version = "0.1.0"
authors = ["will"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "omsupply_server"

[dependencies]
actix-cors = "0.5.4"
actix-web = "3.3.2"
config = "0.11.0"
env_logger = "0.8.3"
futures-util = "0.3.15"
log = "0.4.14"
juniper = "0.15.5"
juniper_actix = "0.2.4"
serde = "1.0.126"

[dependencies.sqlx]
version = "0.4.1"
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "migrate",
    "offline"
]