[package]
name = "repository"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
domain = { path = "../domain" }

chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4.7", default-features = false, features = ["sqlite", "postgres", "r2d2", "numeric", "chrono"] }
diesel-derive-enum = { version = "1.1.1", features = ["sqlite", "postgres"] }
diesel_migrations = "1.4.0"
futures-util = "0.3.15"
libsqlite3-sys = { version = "0.22.2", features = ["bundled"] }
uuid = { version = "0.8", features = ["v4"] }
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0.66"
thiserror = "1"

[dev-dependencies]
actix-rt = "1.1.1" # for Tokio 0.2

[features]
postgres = []
sqlite = []