on: workflow_dispatch
name: Server Test manual

jobs:
  build_and_test:
    name: Remote Server Tests (sqlite)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=sqlite --manifest-path server/Cargo.toml
